"""Scene descriptions for AI-generated Health photos. Key = current WordPress media ID (or new-<pageID>)."""
SCENES = {
# Bariatric
'879': 'A friendly female doctor in a bright consultation room discussing a weight-loss plan with an adult patient, tablet in hand',
'878': 'Adult woman in casual clothes holding out the waistband of jeans that have become too big, neutral light background, face not visible',
'877': 'Close-up of hands measuring a waist with a soft tape measure over a fitted sports top',
'880': 'Adult woman walking outdoors on a sunny path, seen from behind, healthy active lifestyle',
# Check-up
'881': 'Doctor measuring an adult patient’s blood pressure with a modern cuff in a calm, bright clinic',
'883': 'Middle-aged man having a relaxed check-up conversation with a doctor in a modern clinic',
'884': 'Middle-aged woman smiling during a check-up consultation with a female doctor in a modern clinic',
# Clinical intros
'741': 'Smiling adult patient in a modern dental chair talking with a dentist, bright clean dental clinic',
'760': 'Doctor examining the scalp of a man with thinning hair using a handheld dermatoscope, planning a hair transplant',
'857': 'Woman in a modern aesthetic clinic looking calmly into a hand mirror during a consultation',
'872': 'Woman lying relaxed on a treatment bed receiving a gentle facial device treatment, gloved hands of a practitioner',
'882': 'Adult woman relaxing in a comfortable armchair in a spa-like clinic while receiving an IV infusion, drip bag visible',
# Dental
'742': 'Close-up of a natural, bright smile of an adult woman, soft daylight',
'744': 'Dentist showing a dental implant model to a patient in a modern clinic',
'740': 'Dental model of a full-arch implant bridge on a clean white surface, studio light',
'745': 'Dental technician hands polishing a ceramic crown in a dental laboratory',
'743': 'Dental model with implant-supported denture next to dental instruments, clean studio light',
'746': 'Woman smiling with a teeth-shade guide held next to her teeth in a dental clinic',
'968': 'Close-up of a smile with natural-looking white veneers, soft studio light',
'969': 'Dentist gently examining gums with a dental mirror, patient relaxed in the chair',
'971': 'Dentist and assistant treating a smiling male patient in a modern dental chair',
'970': 'Modern dental treatment room with chair, lamp and monitor, no people',
'972': 'Woman gently touching her jawline, calm portrait in a clinic, soft light',
'975': 'Woman holding her cheek and jaw in mild discomfort, neutral background',
'974': 'Close-up of a smiling teenager with clear dental braces',
# Hair
'763': 'Doctor analysing a man’s scalp with a digital trichoscope, image shown on a monitor',
'752': 'Close-up of a medical team performing an FUE hair transplant on the back of a man’s head, clean sterile setting, no blood',
'753': 'Well-groomed man with a full, neat beard, studio portrait',
'754': 'Close-up of a woman’s eye area with full, natural eyebrows',
'973': 'Doctor with magnifying loupes working on a patient’s scalp in a modern hair clinic, sterile and clean',
'976': 'Doctor explaining the hair transplant plan to a male patient using a tablet',
'977': 'Back of a man’s head showing thinning hair, soft studio light',
'764': 'Practitioner applying a serum treatment to a woman’s scalp with gloved hands',
'755': 'Practitioner giving a scalp mesotherapy treatment to a relaxed woman',
'979': 'Woman relaxing under a red LED light therapy device, warm red glow',
'978': 'Laboratory centrifuge with blood sample tubes for PRP preparation, clean clinical light',
# Hospital specialties
'894': 'Doctor kindly holding the hand of an adult patient in a hospital room, supportive cancer care',
'895': 'Cardiologist performing an echocardiogram on a patient lying on an examination bed',
'896': 'Orthopaedic doctor examining a patient’s knee in a bright clinic',
'897': 'Embryologist working at a microscope in a modern IVF laboratory',
'898': 'Neurosurgeon reviewing a brain MRI on a large screen',
'899': 'Patient having an eye examination at a slit lamp with an ophthalmologist',
'900': 'Surgical team in a modern operating room, calm and clean, faces masked',
# IV
'885': 'IV infusion bag with a clear vitamin solution on a stand, bright clinic',
'886': 'Close-up of a hand with an IV cannula resting on a white blanket',
'887': 'Woman with long, shiny, healthy hair, soft studio light',
'888': 'Smiling woman with glowing skin in a white robe, bright spa setting',
'889': 'Woman in sportswear tying her running shoes, active lifestyle',
'890': 'Fresh oranges and lemons in a bowl, vitamin C theme, bright kitchen light',
'891': 'Adult hands resting on a knee, calm and relaxed, soft light',
'892': 'Woman resting hands on her stomach, wellbeing theme, light clothing',
'893': 'Green smoothie with fresh fruit and vegetables on a wooden table',
'980': 'Fresh berries in a bowl, antioxidant theme, natural light',
# Aesthetics
'873': 'Practitioner with gloves giving a small forehead injection to a relaxed woman, clean clinic',
'874': 'Aesthetic doctor assessing the lips and chin of a woman in a treatment chair',
'966': 'Microneedling facial treatment on a relaxed woman, gloved hands, clean clinic',
'965': 'Skin-care serum bottle with dropper on a white marble surface, soft light',
# Plastic
'858': 'Woman holding a tape measure around her waist, wearing jeans and a crop top, face not shown',
'859': 'Side profile of a woman’s face and nose, soft natural light',
'860': 'Plastic surgeon consulting a woman in a bright clinic, discussing a treatment plan',
'861': 'Woman in a white crop top and jeans, torso, tasteful and modest, face not shown',
'862': 'Woman wrapped in a white towel in a bright bathroom, shoulders and back, modest',
'863': 'Man in a grey t-shirt with a hand on his chest, black and white, modest',
'864': 'Woman doing an arm exercise with a light dumbbell in a bright gym, seen from behind',
'865': 'Woman stretching in leggings in a bright, empty studio',
'866': 'Woman’s legs relaxing by a swimming pool, summer light',
'867': 'Close-up of a woman’s eye and upper eyelid, natural skin',
'868': 'Smiling mature woman with natural skin, warm portrait',
'869': 'Side profile of a woman’s cheek and jawline in warm light',
'962': 'Body-contouring device being used on a woman’s abdomen by a gloved practitioner',
'963': 'Woman in a white shirt, elegant studio portrait, modest',
'964': 'Side view of a woman’s ear and profile, hair tucked back',
'967': 'Woman’s neck and jawline, elegant black and white portrait',
# Departments (intro photos)
'903': 'Haematologist talking with an adult patient in a modern bone-marrow transplant unit',
'901': 'Doctor examining the lower back of an adult patient with back pain',
'904': 'Anaesthesiologist checking monitors next to a patient in a modern operating room',
'936': 'Audiologist fitting headphones on a patient for a hearing test in a sound booth',
'905': 'Pink ribbon on a white background, breast health awareness',
'906': 'Cardiac surgery team in a modern operating room with monitors, masked faces',
'907': 'Pulmonologist looking at a chest X-ray on a light board',
'908': 'Therapist talking with a teenager in a calm, friendly counselling room',
'909': 'Dermatologist examining a patient’s skin with a dermatoscope',
'910': 'Modern hospital emergency entrance with an ambulance at dusk',
'911': 'Surgeon examining a patient’s neck before endocrine surgery',
'912': 'Patient checking blood sugar with a glucose meter, close-up of hands',
'914': 'Surgical team performing laparoscopic abdominal surgery, monitors visible, no blood',
'913': 'Gastroenterologist in an endoscopy suite next to an endoscopy tower',
'915': 'Surgeons in blue scrubs operating under bright surgical lights, masked',
'916': 'Female gynaecologist consulting a woman in a bright clinic',
'918': 'Laboratory technician holding a rack of blood sample tubes',
'917': 'Woman with clear skin in a dermatology consultation, calm portrait',
'919': 'Modern MRI scanner room, clean and bright, no people',
'920': 'Gloved hand holding a vaccine vial, clean clinical background',
'921': 'Microbiologist examining petri dishes in a modern laboratory',
'923': 'Internist listening to a patient’s chest with a stethoscope',
'922': 'Interventional radiology suite with an angiography C-arm and monitors',
'924': 'Patient receiving dialysis in a calm, modern kidney unit',
'926': 'Doctor performing an abdominal ultrasound on a patient',
'925': 'Scientist pipetting DNA samples in a genetics laboratory',
'927': 'Microscope with tissue slides in a histology laboratory',
'928': 'Petri dishes with bacterial cultures on a laboratory bench',
'929': 'Pathologist looking through a microscope in a modern laboratory',
'932': 'Nurse caring for a newborn baby in an incubator in a NICU',
'930': 'Doctor reviewing a kidney ultrasound image on a monitor',
'931': 'Neurologist reviewing brain MRI scans on a screen',
'902': 'Patient lying on a PET-CT scanner table with a technician nearby',
'933': 'Dietitian explaining a healthy meal plan with fresh vegetables on the desk',
'934': 'Pregnant woman having an ultrasound with a doctor, both smiling',
'937': 'Paediatric allergist doing a gentle skin test on a child’s forearm, child calm',
'939': 'Nurse in a protective gown talking with a child in a bright hospital room',
'938': 'Paediatric cardiologist listening to a toddler’s heart with a stethoscope, parent nearby',
'940': 'Doctor measuring a child’s height against a colourful wall chart',
'941': 'Child eating a healthy snack of fruit at a table, bright kitchen',
'943': 'Nurse doing a gentle finger-prick test on a calm child, parent nearby',
'942': 'Teddy bear with a small plaster and syringe on a hospital bed, child vaccination theme',
'944': 'Mother holding a happy toddler at a paediatric clinic',
'945': 'Paediatric neurologist examining a child’s reflexes in a friendly clinic',
'946': 'Parent and child holding hands, walking along a sunny beach, hope theme',
'947': 'Doctor examining a child’s knee joint, child sitting on the examination bed',
'948': 'Teddy bear on a children’s hospital bed, bright friendly ward',
'949': 'Paediatrician examining a smiling baby with a stethoscope',
'935': 'Doctor examining a patient’s neck in a calm consultation room',
'950': 'Woman holding her lower abdomen in mild pain, neutral background',
'951': 'Detailed pregnancy ultrasound scan on a monitor with a pregnant belly in the foreground',
'952': 'Physiotherapist guiding a patient through a knee exercise in a bright rehab gym',
'953': 'Brain MRI scans displayed on a monitor in a radiology reading room',
'954': 'Psychiatrist listening to an adult patient in a calm office',
'956': 'Psychologist and client talking in a cosy, bright therapy room',
'955': 'Radiologist reviewing X-ray images on screens in a reading room',
'957': 'Rheumatologist examining an older patient’s hand joints',
'958': 'Thoracic surgery team in a modern operating room, masked, monitors visible',
'959': 'Doctor performing a thyroid ultrasound on a patient’s neck',
'960': 'Blood donation bags in a clean transfusion centre',
'961': 'Urologist consulting a middle-aged man in a modern office',
# Optional new images for pages that currently share a photo
'new-501': 'Gynaecologist and endocrinologist consulting a young woman together (PCOS clinic)',
'new-504': 'ENT doctor examining a patient’s ear with an otoscope',
'new-545': 'Modern intensive care room with monitors and a nurse checking a patient',
}
